/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    DatetimePicker: typeof import('./src/components/common/DatetimePicker.vue')['default']
    KanbanBoard: typeof import('./src/components/kanban/KanbanBoard.vue')['default']
    KanbanColumn: typeof import('./src/components/kanban/KanbanColumn.vue')['default']
    LinkField: typeof import('./src/components/common/LinkField.vue')['default']
    PrioritySlider: typeof import('./src/components/common/PrioritySlider.vue')['default']
    ProjectDialog: typeof import('./src/components/common/ProjectDialog.vue')['default']
    RecurrenceEditor: typeof import('./src/components/common/RecurrenceEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutsModal: typeof import('./src/components/common/ShortcutsModal.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TaskAttachments: typeof import('./src/components/task/TaskAttachments.vue')['default']
    TaskCard: typeof import('./src/components/task/TaskCard.vue')['default']
    TaskDetailPanel: typeof import('./src/components/task/TaskDetailPanel.vue')['default']
    TaskQuickAdd: typeof import('./src/components/task/TaskQuickAdd.vue')['default']
    TaskRow: typeof import('./src/components/task/TaskRow.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
}
